### ISSUE TITLE
Stuck on logout

### ISSUE THREAD

**Issue by atpaz** [idempiere/idempiere-swing-client#4]
Hello, 
When i logout, it stoped at idempiere logo. here is trimmed log output :
`10:20:29.444-----------> DB.isBuildOK: Build Version Error 

The program assumes build version 8.2.0.qualifier, but database has build version 8.2.0.202105270707. 
This is likely to cause hard to fix errors. 
Please contact administrator. [1]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jgoodies.looks.common.RenderingUtils (file:/home/sapta/idempiere-dev/source/idempiere-swing-client/org.adempiere.ui.swing/lib/looks.jar) to method sun.swing.SwingUtilities2.drawStringUnderlineCharAt(javax.swing.JComponent,java.awt.Graphics,java.lang.String,int,int,int)
WARNING: Please consider reporting this to the maintainers of com.jgoodies.looks.common.RenderingUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Loading...
10:20:55.052===========> DB.getDatabase: No Database Connection [89]

10:20:55.052===========> DB.getDatabase: No Database Connection [89]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.compiere.model.POInfo.buildSelect(POInfo.java:820)
	at org.compiere.model.Query.buildSQL(Query.java:699)
	at org.compiere.model.Query.firstOnly(Query.java:345)
	at org.compiere.model.MLanguage.get(MLanguage.java:75)
	at org.compiere.model.MLanguage.get(MLanguage.java:62)
	at org.compiere.util.DisplayType.getDateFormat(DisplayType.java:622)
`

**Comment by dram** [comment]
Hi @Sapta7,

Please following instructions in page [1] to create an issue in JIRA [2], especially, please include detailed steps to reproduce your problem.

Thanks!

[1] https://wiki.idempiere.org/en/Bug_Reporting_Guidelines
[2] https://idempiere.atlassian.net/
